<footer>
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-6 footerBox">
            <p class="copyRight">&copy; Team 26</p>
            <p>
                <a href="contactus.php">Contact Us</a> | 
                <a href="affiliated.php">Affiliate Sites</a> | 
                <a href="index.php">Members Login</a> | 
                <a href="register.php">Register</a>
            </p>
        </div>
        <div class="col-md-3"></div>
    </div>
</footer>